In [4]:
from pathlib import Path
import numpy as np
import pandas as pd

from sklearn.utils import resample

from sklearn.impute import SimpleImputer

from sklearn.pipeline import Pipeline

from sklearn.compose import ColumnTransformer

from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
import xgboost as xgb

from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.model_selection import train_test_split

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score

# from sklearn.inspection import permutation_importance

import time

import joblib

In [5]:
## Folder path
folder_path = Path.cwd().joinpath('data')

In [6]:
## Read training and validation data
train_val_data = pd.read_csv(folder_path.joinpath('train_val_data.csv'))
train_val_data.head()

                                           msno  is_churn  ...  num_unq  total_secs
0  YSs/vsH+AL1WRvlkoLDGFT9wWihtQnqQZuKhqdcybm0=         0  ...   2912.0  866766.109
1  WxkFqbfXFSQgzlLld/tgOEFA9oGpf7JmPgsaMryCZWg=         0  ...     33.0    6766.055
2  58GesZdrmqPIpKnmdzPnUpw07joB4w8ayPNVfhMPPY4=         0  ...   1060.0  318577.925
3  4LqpGjJ/MUOT3a0WEcSUI6xEykQACYUX0pCPm0xgVsg=         1  ...    560.0  137037.344
4  limE8R97wWE+cNSl8CXf0CG/wmI4m1WaZQYPxcjz184=         0  ...    399.0  125289.625

[5 rows x 22 columns]

In [7]:
## Read test data
test_data = pd.read_csv(folder_path.joinpath('test_data.csv'))
test_data.head()

                                           msno  is_churn  ...  num_unq  total_secs
0  /lUtWg8ExxX7WttR/T0UEV5ZmHSjlI+2kEbHdOLQu4o=         0  ...    109.0   51682.863
1  ZKuhr2ZHSE6jAd25Mv1DC/f7q2oZUV9NpxF//1KAC/E=         0  ...    180.0   33348.512
2  Kea1xZZjKRAB3aaYIB1BSM580q2pqxxW/dYId7fEcqU=         0  ...    356.0   85705.528
3  IesOUKSq3onwcJe/MXEBAEw0U/8+qhFa4GQPAxm8EAo=         0  ...    608.0  163959.090
4  HWAZShjWZK98M68I5CJq03m7Mgiq/vmN53/GkXGi4+E=         0  ...    132.0   34568.674

[5 rows x 22 columns]

In [8]:
train_val_data.dtypes

msno                       object
is_churn                    int64
payment_method_id         float64
payment_plan_days         float64
plan_list_price           float64
actual_amount_paid        float64
is_auto_renew             float64
transaction_date           object
membership_expire_date     object
is_cancel                 float64
city                      float64
bd                        float64
gender                     object
registered_via            float64
registration_init_time     object
num_25                    float64
num_50                    float64
num_75                    float64
num_985                   float64
num_100                   float64
num_unq                   float64
total_secs                float64
dtype: object

In [9]:
## Percentage of NA values for each column
(train_val_data.isna()).mean() * 100

msno                       0.00000
is_churn                   0.00000
payment_method_id          3.85449
payment_plan_days          3.85449
plan_list_price            3.85449
actual_amount_paid         3.85449
is_auto_renew              3.85449
transaction_date           3.85449
membership_expire_date     3.85449
is_cancel                  3.85449
city                      11.32785
bd                        11.32785
gender                    59.93507
registered_via            11.32785
registration_init_time    11.32785
num_25                    22.29340
num_50                    22.29340
num_75                    22.29340
num_985                   22.29340
num_100                   22.29340
num_unq                   22.29340
total_secs                22.29340
dtype: float64

In [10]:
## Split train_val data into train and val data
train_df, val_df = train_test_split(train_val_data, test_size=0.15, random_state=10)

In [11]:
train_df.head()

                                                msno  ...  total_secs
66983   5b20roNDwa3p3z0Y3aWtYMuG0dGRB0tDAIwiYHm38mw=  ...  196341.137
242418  O+PqZOEN+6Fq5wr+dpntGdnzaSpnUPUIj3el0IAylYY=  ...  194550.134
455493  lNmJE7vrHFf9/Zp2iGgayiNJMt9Wi17i7EHTBenArIY=  ...  570913.226
866243  Zf62RXGDnyehoy837HpuoOQy9WdJFPiltWqBcZP+2F0=  ...   92633.412
83612   rlyej0t+xs1y8MIjClijpXSatK8QOzBI0kok5HO7FtA=  ...  129521.047

[5 rows x 22 columns]

## Data imputation

In [12]:
## Numeric features imputer
numeric_feature_imputer = SimpleImputer(strategy='median')
numeric_columns = ['plan_list_price', 'actual_amount_paid', 'bd', 'num_25', 'num_50', 'num_75', 'num_985', 'num_100', 'num_unq', 'total_secs']

## Categorical features imputer
categorical_feature_imputer = SimpleImputer(strategy='most_frequent')
categorical_columns = ['payment_method_id', 'payment_plan_days', 'is_auto_renew', 'is_cancel', 'city', 'registered_via']

## Constant imputer
constant_imputer = SimpleImputer(strategy='constant', fill_value='not_specified')
constant_impute_column = ['gender']
constant_imputer_pipeline = Pipeline([('imputer', constant_imputer), ('one_hot_encoder', OneHotEncoder())])

## Combine all the imputation transformers with Column Transformer
column_transformer = ColumnTransformer(transformers=[('numeric_imputer', numeric_feature_imputer, numeric_columns),
                                                     ('categorical_imputer', categorical_feature_imputer, categorical_columns),
                                                     ('constant_imputer', constant_imputer_pipeline, constant_impute_column)])

## Final pipeline with scaling
pipeline = Pipeline([('imputation_step', column_transformer), ('scale_data', StandardScaler())])

In [14]:
pipeline.fit(train_df)

Pipeline(memory=None,
         steps=[('imputation_step',
                 ColumnTransformer(n_jobs=None, remainder='drop',
                                   sparse_threshold=0.3,
                                   transformer_weights=None,
                                   transformers=[('numeric_imputer',
                                                  SimpleImputer(add_indicator=False,
                                                                copy=True,
                                                                fill_value=None,
                                                                missing_values=nan,
                                                                strategy='median',
                                                                verbose=0),
                                                  ['plan_list_price',
                                                   'actual_amount_paid', 'bd',
                                                   'num_25', 'num_50', 'num_7...
                                                                   SimpleImputer(add_indicator=False,
                                                                                 copy=True,
                                                                                 fill_value='not_specified',
                                                                                 missing_values=nan,
                                                                                 strategy='constant',
                                                                                 verbose=0)),
                                                                  ('one_hot_encoder',
                                                                   OneHotEncoder(categories='auto',
                                                                                 drop=None,
                                                                                 dtype=<class 'numpy.float64'>,
                                                                                 handle_unknown='error',
                                                                                 sparse=True))],
                                                           verbose=False),
                                                  ['gender'])],
                                   verbose=False)),
                ('scale_data',
                 StandardScaler(copy=True, with_mean=True, with_std=True))],
         verbose=False)

In [15]:
## Pre-process train data
x_train_tot = pipeline.transform(train_df)
y_train_tot = train_df.is_churn.values

In [16]:
x_val = pipeline.transform(val_df)
y_val = val_df.is_churn.values

## Downsample data

In [17]:
## Downsample data with class 0 
x_train_0 = resample(x_train_tot[y_train_tot == 0], replace=False, n_samples=int(len(x_train_tot[y_train_tot==0])*0.30), random_state=10)

x_train = np.vstack((x_train_0, x_train_tot[y_train_tot == 1]))
y_train = np.hstack((np.zeros(len(x_train_0), dtype=int), np.ones(len(x_train_tot[y_train_tot == 1]), dtype=int)))

In [18]:
## This helper function explains the confusion matrix obtained from confusion_matrix method
def confusion_matrix_report(confusion_arr:np.ndarray):
    """
        Function to explain the confusion matrix 
        
        Parameters
        -----------
        confusion_arr  :   np.ndarray containing values of confusion matrix
        
        Returns a dictionary explaining each value in confusion_arr
    """
    return {"True Positive": confusion_arr[1,1],
            "False Positive": confusion_arr[0,1],
            "True Negative": confusion_arr[0,0],
            "False Negative": confusion_arr[1,0]}

## ML autopilot 
This ML autopilot runs as follows:

* For the models specified, find the best set of parameters (from the specified list of parameters to search) using grid search and cross validation
* For each of the models, the best performing version is stored which can be used for evaluation

In [19]:
class MLAutopilot:
    def __init__(self, model_name=None, model_params=None):
        if model_name is not None and model_params is not None:
            self.models = model_names
            self.model_params = model_params
        else:      
            self.models = {'Logistic Regression': LogisticRegression(random_state=1, n_jobs=-1),
                           'Decision Tree Classifier': DecisionTreeClassifier(random_state=3),
                           'Random Forest Classifier': RandomForestClassifier(random_state=4, n_jobs=-1),
                           'Gradient Tree Boosting Classifer': GradientBoostingClassifier(random_state=5),
                           'XGBoost Classifier': xgb.XGBClassifier(random_state=6, n_jobs=-1)}

            self.params = {'Logistic Regression': [{'penalty': ['l2'], 'C': [1.0, 0.5]},
                                                   {'penalty': ['l1'], 'C': [1.0, 0.5], 'solver': ['liblinear']}],
                           'Decision Tree Classifier': {'criterion': ['gini', 'entropy'], 'min_samples_split': [2,5,10,25,50], 'min_samples_leaf': [1, 5, 10, 25]},
                           'Random Forest Classifier': {'n_estimators': [100, 250, 500, 1000], 'criterion': ['gini', 'entropy'], 'min_samples_split': [2,5,10,25,50], 
                                                        'min_samples_leaf': [1, 5, 10, 25]},
                           'Gradient Tree Boosting Classifer': {'loss': ['deviance', 'exponential'], 'learning_rate': [0.1, 0.05, 0.01, 0.001],
                                                                'n_estimators': [100, 200, 500, 1000], 'subsample': [1.0, 0.8, 0.6, 0.4], 'max_depth': [3, 5, 10]},
                           'XGBoost Classifier': {'n_estimators': [100, 500, 1000], 'max_depth': [3, 5, 10], 'learning_rate': [0.5, 0.1, 0.01, 0.001],
                                                  'subsample': [0.6, 0.8, 1.0]}}
          

        self.models_grid_search = {}
        self.models_best_model = {}
        self.models_cv_score = {}


    def run_automl(self, x_train: np.ndarray, y_train: np.ndarray, scoring_metric: str = 'f1', cv: int = 5, param_search_type: str = 'grid'):
        """
            Method to run AutoML
        """
        print(f"Evaluation metric: {scoring_metric}")
        print(f"Number of models to run: {len(self.models)}")
        for n, model in enumerate(self.models.items()):
            print(f"Running {model[0]} model")
            mod_time = time.time()
            
            if param_search_type == 'grid':
                # Perform Grid Search
                self.models_grid_search[model[0]] = GridSearchCV(estimator=self.models[model[0]], param_grid=self.params[model[0]], 
                                                                       scoring=scoring_metric, cv=cv)
            elif param_search_type == 'random':
                # Perform Randomized Grid Search
                self.models_grid_search[model[0]] = RandomizedSearchCV(estimator=self.models[model[0]], param_distributions=self.params[model[0]], 
                                                                       scoring=scoring_metric, cv=cv)
            else:
                raise TypeError("Parameter Search type must be either grid or random")
            
            self.models_grid_search[model[0]].fit(x_train, y_train)
            
            # Store best estimator based on Grid CV search
            self.models_best_model[model[0]] = self.models_grid_search[model[0]].best_estimator_
            
            # Store CV score based on average CV score of the best model
            self.models_cv_score[model[0]] = self.models_grid_search[model[0]].best_score_

            print(f"Model run time: {round(time.time() - mod_time, 2)} seconds")
            print(f"CV score: {round(self.models_cv_score[model[0]], 4)}")

    
    def get_prediction(self, pred_data:np.ndarray, model_name:str):
        """
            Method to get prediction from trained model
        """
        if not isinstance(model_name, str) or not isinstance(pred_data, np.ndarray):
            raise AssertionError("Model name must be a string and pred_data must be a numpy.ndarray")

        ## Compute and return the predictions with the best model for model_name
        return self.models_best_model[model_name].predict(pred_data)


    def get_score(self, pred_data:np.ndarray, truth_label:np.ndarray, model_name:str, metric:str):
        """
            Get scores for an input dataset
        """
        if not isinstance(model_name, str) or not isinstance(metric, str) or not isinstance(pred_data, np.ndarray) or not isinstance(truth_label, np.ndarray):
            raise AssertionError("Model name and metric must be a string, and pred_data and truth_label must be a numpy.ndarray")
        
        ## Step 1: Compute predictions
        predictions = self.models_best_model[model_name].predict(pred_data)

        ## Step 2: Compute metric
        return eval(metric)(truth_label, predictions)
                        
                  
    def save_model(self, model_name: str, save_loc: str=None):
        """
            Method to save ML model

            Parameters
            -----------
            model_name  :  str containing name of the model to save
            save_loc    :  str containing location to save model

            Returns a string if model has been saved successfully
        """
        if save_loc is None:
            Path.cwd().joinpath('saved_model').mkdir(parents=True, exist_ok=True)
            save_loc = Path.cwd().joinpath('saved_model', model_name+'.pkl')

        try:
            joblib.dump(self.models_best_model[model_name], save_loc)
        except:
            raise IOError("Could not save the model. Check model name and file path")
        else:
            print("Model saved successfully!")

In [20]:
## Run ML pipeline (Takes about a day to run all the models)
ml_autopilot = MLAutopilot()
ml_autopilot.run_automl(x_train, y_train, 'f1', 5, 'random')

Evaluation metric: f1
Number of models to run: 5
Running Logistic Regression model

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:281: UserWarning: The total space of parameters 4 is smaller than n_iter=10. Running 4 iterations. For exhaustive searches, use GridSearchCV.
  % (grid_size, self.n_iter, grid_size), UserWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:1539: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 2.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:1539: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 2.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:1539: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 2.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:1539: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 2.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:1539: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 2.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:1539: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 2.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:1539: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 2.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:1539: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 2.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:1539: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 2.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:1539: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 2.
  " = {}.".format(effective_n_jobs(self.n_jobs)))
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:1539: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 2.
  " = {}.".format(effective_n_jobs(self.n_jobs)))

Model run time: 148.56 seconds
CV score: 0.5682
Running Decision Tree Classifier model
Model run time: 176.34 seconds
CV score: 0.7918
Running Random Forest Classifier model
Model run time: 10230.52 seconds
CV score: 0.7991
Running Gradient Tree Boosting Classifer model
Model run time: 29230.81 seconds
CV score: 0.7986
Running XGBoost Classifier model
Model run time: 11699.77 seconds
CV score: 0.7983

In [32]:
## Save trained models
for model_name in ml_autopilot.models_best_model:
    save_location = folder_path.parent.joinpath('saved_models', model_name+'.pkl')
    ml_autopilot.save_model(model_name, save_location)
print("Models saved!")

Model saved successfully!
Model saved successfully!
Model saved successfully!
Model saved successfully!
Model saved successfully!
Models saved!